### ISSUE TITLE
Add note of certificate

### ISSUE THREAD

**Issue by KourokiTakuto** [personium/ansible#65]
Add note of certificate

Refer to the description on the form of the following certificate and secret key
En
https://doc.cloud.global.fujitsu.com/lib/personiumservice/en/manual_en/00_manual.html#sect8

Ja
https://doc.cloud.global.fujitsu.com/lib/personiumservice/jp/manual/00_manual.html#sect8

**Comment by naoya-mokudai** [comment]
Create certificate registration procedure when Let's Encrypt is used.
