### ISSUE TITLE
Failed to install in Per Cell version

### ISSUE THREAD

**Issue by dixonsiu** [personium/ansible#80]
Similar [issue](https://github.com/personium/setup-vagrant/issues/42) in setup-vagrant

**Comment by tochi-y** [comment]
Per Cell version works normally on public cloud. Maybe other cause or setup-vagrant issue.

**Comment by shimono** [comment]
We close this issue since this seems to be caused by an external reason.
If any specific issue is spotted, please reopen this issue and add more details.
